version: '3.7'
services:

  configserver:
    image: "mzegarra/lab03sut"
    #ports:
    #  - 8888:8888
    volumes:
      - ./config-server.jks:/config-server.jks
    environment:
      GIT_URI: "https://github.com/mzegarras/tci-config-dev.git"
      GIT_USER: "mzegarra"
      GIT_PWD: "M0ssyUPC12@"
      KEYSTORE_PWD: "YOU_KEYSTORE_PASSWORD"
      KEYSTORE_ALIAS: "YOU_CONFIG_SERVER_KEY"
      KEYSTORE_SECRET: "YOU_KEYSTORE_PASSWORD"
  db:
    image: mysql:5.7
    restart: always
    #ports:
    #  - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db01
      MYSQL_USER: lab01user
      MYSQL_PASSWORD: lab01userpwd
    healthcheck:
      test: "/etc/init.d/mysql status"
      timeout: 20s
      interval: 10s
      retries: 10

  cache:
    image: redis:4-alpine
    command: sh -c 'echo "requirepass password" | redis-server -'
    #ports:
    #  - 6379:6379
  cache-client:
    image: redis:4-alpine
    command: redis-cli -h cache
    depends_on:
    - cache

  bus:
    image: "rabbitmq:3-management"
    #environment:
      #RABBITMQ_DEFAULT_USER: "rabbitmq"
      #RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./rabbitmq_definitions.json:/etc/rabbitmq/definitions.json:ro

  gates:
    image: "mzegarra/gatessut"
    ports:
      - 8080:8443
    depends_on:
      - lab01

  lab01:
    image: "mzegarra/lab01sut:latest"
    #ports:
    #  - 8080:7070
    environment:
      SERVER_CONFIG_ENABLED: "true"
      SERVER_CONFIG_URL: "http://configserver:8888"
      SERVER_CONFIG_FAIL_FAST: "true"
      INITIAL_INTERVAL: 1000
      MULTIPLIER: 2.0
      MAXINTERVAL: 30000
      MAXATTEMPTS: 100
    depends_on:
      - db
      - configserver
      - bus
      - cache-client

  lab02:
    image: "mzegarra/lab02sut"
    environment:
      SERVER_CONFIG_ENABLED: "true"
      SERVER_CONFIG_URL: "http://configserver:8888"
      SERVER_CONFIG_FAIL_FAST: "true"
      INITIAL_INTERVAL: 1000
      MULTIPLIER: 2.0
      MAXINTERVAL: 30000
      MAXATTEMPTS: 100
    depends_on:
      - configserver
      - bus
      - cache-client

  lab05:
    image: "mzegarra/lab05sut:latest"
    ports:
      - 9999:9999
    environment:
      SERVER_CONFIG_ENABLED: "true"
      SERVER_CONFIG_URL: "http://configserver:8888"
      SERVER_CONFIG_FAIL_FAST: "true"
      INITIAL_INTERVAL: 1000
      MULTIPLIER: 2.0
      MAXINTERVAL: 30000
      MAXATTEMPTS: 100
    depends_on:
      - configserver
