apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: lab06
spec:
  hosts:
  - "*"
  gateways:
  - lab06-gateway
  http:
  - match:
    - uri:
        prefix: /accounts
    route:
      - destination:
          host: lab06
          subset: v1
          port:
            number: 7070
        weight: 70
      - destination:
          host: lab06
          subset: v2
          port:
            number: 7070
        weight: 30
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: lab06
spec:
  host: lab06
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2